### ISSUE TITLE
make CLI authentication case-insensitive

### ISSUE THREAD

**Issue by swanderz** [dbt-msft/dbt-sqlserver#100]
in  #99, we found out that users assume that `authentication: CLI` can also be given as `authentication: cli` which is not the case.

@JCZuurmond... if you're interested 👀 

Spitball idea, but maybe we add an `.upper()` to the this snippet below. something like:
```python
if type_auth.upper() in AZURE_AUTH_FUNCTIONS.keys()
```

https://github.com/dbt-msft/dbt-sqlserver/blob/0d529de2641cc7e3f84bab47e22a9f4c80629bbd/dbt/adapters/sqlserver/connections.py#L281-L288

**Comment by JCZuurmond** [comment]
@swanderz : That would indeed solve the problem for when authentication type is `cli` instead of `CLI` (or `cLi` for that matter). However it would not make the other authentication types case insensitive.

I have the urge to restructure some code first so that we can add (py)tests. It would make me more confident about changing code without breaking it.

However, if we prefer to do a quick fix first, then that is ok with me.

**Comment by swanderz** [comment]
no urgency to make a hotfix, given that this issue is documented and easily fixed. more tests would be great -- thanks for offering. Happy to add any tests you write to CircleCI.
