### ISSUE TITLE
re-implement Compiler._add_ctes() method

### ISSUE THREAD

**Issue by swanderz** [dbt-msft/dbt-sqlserver#137]
Doing this would enable:
- ephemeral materialization, and
- usage of CTEs in data tests

Fixes:
- #26, and
- https://github.com/dbt-msft/dbt-synapse/issues/25

@jtcohen6 do you mind taking a rough stab at templating this out? In https://github.com/dbt-msft/dbt-synapse/pull/29, you already did this for dbt-synapse, but since I re-wrote the Git history, I can't see you actual changes.

### **_update_** --

https://github.com/dbt-msft/dbt-synapse/commit/9180da5a6d092c6b4b22d5388aa6592d2b9d77c4 shows what was done, @jtcohen6 can you just confirm that this approach still stands?

**Comment by jtcohen6** [comment]
I think these are going to be two separate issues going forward. The solution for data tests should be much more straightforward—newly, however, it will be relevant to schema tests as well.

### Tests

In v0.20.0, dbt will be templating data tests via a `'test'` materialization, defined [here](https://github.com/fishtown-analytics/dbt/blob/develop/core/dbt/include/global_project/macros/materializations/test.sql). This will be relevant for both data tests and schema tests. In most cases, [the final test query](https://github.com/fishtown-analytics/dbt/blob/abe8e839458d0288f76cb6950e79c77e3b1627cc/core/dbt/include/global_project/macros/materializations/test.sql#L42-L49) will look something like:
```
select
  count(*) as failures,
  count(*) !=0 as should_warn,
  count(*) !=0 as should_error
from (
  ... actual test SQL goes here ...
) dbt_internal_test
```
That's a subquery, which is new for both data tests (previously a CTE) and schema tests (previously no wrapper). I'm going to guess that, in T-SQL, [you cannot use CTEs nested within a subquery](https://stackoverflow.com/questions/1914151/how-we-can-use-cte-in-subquery-in-sql-server), just as you cannot use CTEs nested within a CTE. Believe it or not, some SQL syntaxes are happy with the former even if they don't support the latter.

So you may need to override the `'test'` materialization for `sqlserver` + `synapse`, which is totally doable. (Macro inheritance doesn't work the same for materializations as it does for dispatch, so you may need to reimplement it in both places.) I imagine one possible approach would be to create the test SQL as a view or temporary table first, and then select from the view/temp object in the final query. That's very similar to what `dbt test --store-failures` does, except with permanent/persisted tables.

### Ephemeral models

The _general_ approach outlined in https://github.com/dbt-msft/dbt-synapse/commit/9180da5a6d092c6b4b22d5388aa6592d2b9d77c4 is still the same, though I was doing it on easy mode, and didn't actually try to solve for ephemeral model compilation :)

The mechanism is: [reimplement the compiler](https://github.com/dbt-msft/dbt-synapse/commit/9180da5a6d092c6b4b22d5388aa6592d2b9d77c4#diff-f5edefcace852d4b7f256956b00c049883a49be1d8216dd2438480b8f1e55c09R43-R45), define a new one (like in `dbt/adapters/sqlserver/compilation.py`), and reimplement methods like [`_inject_ctes_into_sql `](https://github.com/fishtown-analytics/dbt/blob/abe8e839458d0288f76cb6950e79c77e3b1627cc/core/dbt/compilation.py#L191`) and [`_recursively_prepend_ctes`](https://github.com/fishtown-analytics/dbt/blob/abe8e839458d0288f76cb6950e79c77e3b1627cc/core/dbt/compilation.py#L252).

Taking a step back: In order to support ephemeral models with CTEs on SQLServer and Synapse, given that T-SQL doesn't support CTEs nested inside either CTEs or subqueries, would we have to take the same approach as the one outlined above?

Namely, instead of recursively prepending ephemeral models as CTEs to the start of the query:
```sql
with  __dbt__cte__ephemeral_model as (


with my_cte as (
    
    select 1 as id
    
)

select * from my_cte
),ephemeral_model as (

select * from __dbt__cte__ephemeral_model

),

another_cte as (
    
    select 2 as id
    
)

select * from ephemeral_model
union all
select * from another_cte
```

Recursively prepend them as temp tables, to be executed in-transaction with the body of the query:
```sql
create table #ephemeral_model as (


with my_cte as (
    
    select 1 as id
    
)

select * from my_cte
);

with ephemeral_model as (

select * from #ephemeral_model

),

another_cte as (
    
    select 2 as id
    
)

select * from ephemeral_model
union all
select * from another_cte
```

Or is there another approach I'm missing?
