### ISSUE TITLE
no capability to add ORDER BY table models

### ISSUE THREAD

**Issue by swanderz** [dbt-msft/dbt-sqlserver#144]
a [user in dbt Slack](https://getdbt.slack.com/archives/CMRMDDQ9W/p1624375182070500) asks:
> Hi all, is there a way to specify "sort" column(s) or order by for models created in SQL Server? When I put in an order by clause I get the following error:
> ```
> [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]
> The ORDER BY clause is invalid in
> views, inline functions, derived tables, subqueries, and common table expressions,
> unless TOP, OFFSET or FOR XML is also specified.
> ``` 

Because we're using the `SELECT * INTO` DML for our model generation, if you include an `ORDER BY` in the SELECT query of a model, you'll get the above error. But I'm confused because the [docs](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-ver15#interoperability) say it should be allowed, but isn't guaranteed...
> When used with a SELECT...INTO or INSERT...SELECT statement to insert rows from another source, the ORDER BY clause does not guarantee the rows are inserted in the specified order.

https://github.com/dbt-msft/dbt-sqlserver/blob/679b3515e9f056879c6609c78bb62791716c450a/dbt/include/sqlserver/macros/adapters.sql#L160-L161

**Comment by mikaelene** [comment]
I think this is due to that we are creating a temp-view in the middle of this. The tmp_relation above. A view can not have order by.

**Comment by jeroen-mostert** [comment]
There is only one scenario where `ORDER BY` in an `INSERT` makes sense, and that's for guaranteeing that `IDENTITY` columns are assigned values in order. In all other cases this does not do what you might want it to do -- in particular, every time you `SELECT` from a table you must specify an `ORDER BY` if you want an order, otherwise the engine is free to rearrange things as it sees fit (and it will, if the table is a columnstore, or parallelism is involved, or it can reuse a scan in progress from another query), so whatever order you think you may have gotten from the insert will not be useful anyway (and that's before we consider rows being moved through deletes and updates). People often fall into the trap of thinking there's a "natural physical order" that you're guaranteed to get if you do `SELECT *` with no `ORDER BY`, but there isn't.

So this is probably not useful to enable unless there really is a use case of building models with `IDENTITY` columns (unlikely, since `ROW_NUMBER()` gives you predictable values as well), and even then, as Mikael notes, you'd need to not use a view. (In olden days `SELECT TOP(100) PERCENT ... ORDER BY` could be used as a trick to circumvent this restriction, but while that's still allowed syntactically, the optimizer simply pretends you didn't write an `ORDER BY` in that case.)

**Comment by swanderz** [comment]
I thought it would be possible (and maybe even _useful_) to add a custom configuration, `order_by`, that could be used like below. However I tried it just now and the `ORDER BY` did nothing and the rows are returned in ascending order.

@mikaelene can you remember why we don't use temp tables and instead use views? I can't remember...

```sql
-- models/example.SQL
{{
  config(
    order_by = 'id DESC,
    )
}}

SELECT 1 as id
UNION
SELECT 2 as id
```

calling `dbt run -m example` would run the following SQL:

```sql
create view "ajs"."example__dbt_tmp_temp_view" as

SELECT 1 as id
UNION
SELECT 2 as id;

SELECT * INTO "SalesOps"."ajs"."example__dbt_tmp"
FROM "SalesOps"."ajs"."example__dbt_tmp_temp_view"
-- this would be the line magically "injected"
ORDER BY id DESC
```

**Comment by lkell** [comment]
I originally requested a sorting mechanism in the slack channel because I thought it would be convenient to my data mart's end users to have a default row ordering on specific tables/models. However, learning more about the SQL behavior makes me realize that this may not be feasible or as useful as I had thought (@jeroen-mostert's  comment was very helpful in that regard). Alternatively, I can perhaps use a clustered index to achieve what I want? 

In any case, if you decide that allowing for the `ORDER BY` isn't worth it, then I am perfectly happy to drop my original request. I really appreciate you looking into this though!

**Comment by jeroen-mostert** [comment]
Adding a clustered index to the table doesn't convey any (intrinsic) order either. It will often be the case that you will get the clustered index order when you do a `SELECT *` with no `ORDER BY` (especially if the table is small and is never modified), but this is not guaranteed, and your end users should not count on it -- they should always write their own `ORDER BY`, otherwise they might get in the habit of only looking at the top rows and assuming that it's all there when it might not be.

If you really want a default order you can do something like a view that does `SELECT TOP(9223372036854775807) ... FROM table ORDER BY ...` (that number is the largest value that fits a `BIGINT` and should suffice for any table :P), unlike `TOP(100) PERCENT` the optimizer does not ignore this, and if the clustered index supports that order the ordering is "free". It's not exactly elegant, though.

**Comment by mikaelene** [comment]
Closing this, as it is not really feasible, and not desirable.
